name: hSubscription
version: 1.1
main: me.xflyiwnl.hsubscription.HSubscription
api-version: '1.16'
softdepend:
  - PlaceholderAPI

commands:

  subscription:
    description: "Subscription command for users"
    aliases:
      - sub
      - s

  subscriptionadmin:
    description: "Subscription command for admins"
    aliases:
      - subadmin
      - sa